### PR TITLE
Fix for Spotify 1.1.85

### PR DESCRIPTION
**Pull request by itsmeow**
## Fixes

- `Spicetify.ReactDOM`
- React symbols undefined error
- Includes additional symbol fixes from @CharlieS1103

## Known Issues

Lyrics Plus does not work, some type of javascript error I do not have time to investigate.

### CODE REVIEW

**Review by CharlieS1103 — APPROVED** [review]
Looks all good to me!

**Comment by CharlieS1103** [comment]
@ririxidev What do you mean by that?

**Comment by itsmeow** [comment]
commit structure overrated

**Comment by CharlieS1103** [comment]
@itsmeow Agreed 100%, I'm certainly no expert but it seems rather nerdy.

**Comment by afonsojramos** [comment]
It's not about if it nerdy or not. It's about setting standards! @CharlieS1103

**Comment by CharlieS1103** [comment]
@afonsojramos Just holing, was unaware it was so easy to change PR titles.

**Pull request merged**
