### PR TITLE
docs: Updating README.md to be more precise

### PR DESCRIPTION
**Pull request by max12mx13**
Its just not very obvious in my opinion - happy for the text to be changed to whatever you see sensible!

### CODE REVIEW

**Comment by max12mx13** [comment]
Sorry about all the title changes

**Comment by kyrie25** [comment]
Config only displays while you are on the page is self-explanatory.
Settings for an app only needs to be displayed while that app is opened and where the changes can be seen live.
This logic applies for all custom apps and extensions which has its own layout that Spicetify has by default (FAD, Reddit, Lyrics Plus).

So while we appreciate your contribution, this is an unnecessary commit that doesn't really serve any purpose.

**Comment by CharlieS1103** [comment]
I don't actually think it's that clear to be entirely obvious, it seems a bit strange that it randomly appears in the profile menu with zero context or anything provided, so it doesn't seem like a bad idea to inform users of this. @kyrie25

**Comment by kyrie25** [comment]
> it seems a bit strange that it randomly appears in the profile menu with zero context or anything provided

Those settings are only needed while the app is opened and thus only displayed when it is put into effect, that itself is not *zero context*


Pointing out that the settings modal for an app *is* available while using *that same app* is very much obvious. If you do want to inform the users that a config modal exists, then make a complete section about it so it does serve a purpose.

**Comment by max12mx13** [comment]
Where would you suggest we add this section?
Would a README in the CustomApps dir work?

**Comment by kyrie25** [comment]
> Where would you suggest we add this section?
> 
> Would a README in the CustomApps dir work?

This same README at the place the change was added would be fine.

**Comment by max12mx13** [comment]
So what do you suggest to add. I'm not sure

**Comment by CharlieS1103** [comment]
@kyrie25 it just seems odd to me that we would put that in the profile menu, either it should stay permanently inside the profile menu or we should have a second (more visible) settings button that only appears when lyrics plus is opened, such as we have on marketplace. Most users, including myself, aren't used to seeing the profile menu gain and lose options dependent on which page you are on.

**Comment by kyrie25** [comment]
> it just seems odd to me that we would put that in the profile menu, either it should stay permanently inside the profile menu

Scope of where the settings is applied, already said above. There's no reason to change Spotify settings outside the Spotify application where it is not put into use, same reason for that.

> we should have a second (more visible) settings button that only appears when lyrics plus is opened, such as we have on marketplace. Most users, including myself, aren't used to seeing the profile menu gain and lose options dependent on which page you are on.

Lol skill issue. There has only been one user came in and asks where the config is, *most users* don't have the issue you claim they have, for as long as these default Spicetify custom apps been a thing.

**Comment by max12mx13** [comment]
Ok, I just think its not very clear, no need to be rude.

**Comment by kyrie25** [comment]
> Ok, I just think its not very clear, no need to be rude.

That wasn't addressed to you.

**Pull request closed without merging**
