### PR TITLE
fix(lyrics-plus): ignore lang check on none/Genius

### LINKED ISSUE #2435: [Lyrics Plus] Genius page crashes
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.14
- Spicetify version: 2.20.2
```

## This issue has occurred since #2343 was applied.
* Click Genius in lyrics plus
* Select the latest song without some lyrics and open lyrics plus

### 📸 Screenshots

* Click Genius

https://github.com/spicetify/spicetify-cli/assets/91320047/31e15b66-71bd-4971-bced-7dd51910f95f

* Select the latest song without some lyrics and open lyrics plus

https://github.com/spicetify/spicetify-cli/assets/91320047/a91cd5c7-a536-42fc-9374-677d7378d4f9

### PR DESCRIPTION
**Pull request by kyrie25**
Resolves #2435

### CODE REVIEW

**Comment by Lseoksee** [comment]
I checked the corresponding pr and both issues have been resolved!
The reason for the second problem seems to have been that the lyrics are only in Genius, so it automatically brings up the lyrics of Genius.

**Comment by Lseoksee** [comment]
But there's one problem. Changes to Style.css have made the layout of the lyrics lyrics-plus in fullAppDisplay 
weird. Is this intended?


* before
Screenshot 2023-06-26 22-28-53

* after
Screenshot 2023-06-26 22-23-42

**Review by afonsojramos — APPROVED** [review]

**Comment by kyrie25** [comment]
It was just a quick commit so I won’t forget later, I didn’t check thoroughly. 
Will keep that in mind.

**Comment by kyrie25** [comment]
> But there's one problem. Changes to Style.css have made the layout of the lyrics lyrics-plus in fullAppDisplay 
> 
> weird. Is this intended?
> 
> 
> 
> 
> 
> * before
> 
> Screenshot 2023-06-26 22-28-53
> 
> 
> 
> * after
> 
> Screenshot 2023-06-26 22-23-42
> 
> 

That should resolve the issue now.

**Review by rxri — APPROVED** [review]

**Pull request merged**
