### PR TITLE
fix(fad): lyrics plus positioning

### LINKED ISSUE #2416: [fullAppDisplay] The lyrics plus lyrics display is weird
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.13
- Spicetify version: 2.20.1
```

### 📝 Description

- Enable the lyrics plus view in fullAppDisplay.

### 📸 Screenshots

Desktop Screenshot 2023 06 18 - 11 09 25 57

### PR DESCRIPTION
**Pull request by kyrie25**
Resolves #2416 
image
image

### CODE REVIEW

**Comment by WenchenWang** [comment]
how do I solve it ?

**Review by rxri — APPROVED** [review]

**Comment by WenchenWang** [comment]
how to solve it ? still wrong position

**Comment by bachig26** [comment]
@kyrie25 @rxri @Lseoksee this issue hasn't been solved. I've tried completely removing the spicetify and reinstalled but still this issue exist.

**Comment by kyrie25** [comment]
> @kyrie25 @rxri @Lseoksee this issue hasn't been solved. I've tried completely removing the spicetify and reinstalled but still this issue exist.

The issue is only fixed in Spicetify’s Full App Display.

Any other instance of FAD used via Marketplace or other than built-in Full App Display is not our issue.

**Comment by kyrie25** [comment]
Please don’t mention maintainers or other people participating because there is an issue on your end.

**Comment by bachig26** [comment]
> Any other instance of FAD used via Marketplace or other than built-in Full App Display is not our concern.

I've used the built-in official spicetify FAD and also removed them when it doesn't work, then furthermore installed by manually downlading the FAD js file to the Entension folder and installed using the cli command. still not working.

**Comment by kyrie25** [comment]
Attach a screenshot of your `config-xpui`, the issue, and the `About Spotify` modal with the Spicetify list expanded.

**Comment by rxri** [comment]
You use fullAppDisplayMod though. fullAppDisplayMod needs to be fixed separately

**Comment by rxri** [comment]
FAD from marketplace needs to be fixed separately. Like kyrie said:
> Any other instance of FAD used via Marketplace or other than built-in Full App Display is not our concern.

**Comment by kron0800** [comment]
my bad! i thought it was the oficcial one. where can i find the original extension? or is it the full screen button on the bottom left corner? (if that's the case, how do i enable lyrics)

**Comment by kron0800** [comment]
nvm i got it working with spicetify config extensions fullAppDisplay.js

**Pull request merged**
