### PR TITLE
feat(path-utils): try to find custom app folder with `index.js`

### PR DESCRIPTION
**Pull request by SunsetTechuila**
I'm tired of this 

image

### CODE REVIEW

**Comment by SunsetTechuila** [comment]
is anyone going to review this?

**Review by rxri — APPROVED** [review]
if this will really help users, ig we can add this

**Comment by SunsetTechuila** [comment]
not sure about the naming and code style - let me know if you have any comments

**Review by afonsojramos — APPROVED** [review]
Don't really get why we can't just force users to extract to the first level of folders, but I guess it won't hurt anyone 🤷

**Comment by SunsetTechuila** [comment]
> just force users to extract to the first level of folders

How?

**Comment by afonsojramos** [comment]
By not having it work otherwise 😅

**Pull request merged**
