### PR TITLE
feat: `update` rework

### PR DESCRIPTION
**Pull request by afonsojramos**
Following the discussions on #2528 and on Discord, this PR removes the `--check-update` flag and makes the `upgrade`/`update` semi-chainable. Also renamed the old `update` to `refresh` as it felt that it was the word that made the most sense based on what the function did and the PoV of the user.

### CODE REVIEW

**Comment by rxri** [comment]
we need to keep in mind that it will require changing section about upgrading spicetify in docs

**Comment by SunsetTechuila** [comment]
https://github.com/spicetify/spicetify-cli/blob/80b69628dea963ebff73ba6734967ae024b4efb4/jsHelper/spicetifyWrapper.js#L2370
https://github.com/spicetify/spicetify-cli/blob/80b69628dea963ebff73ba6734967ae024b4efb4/jsHelper/spicetifyWrapper.js#L2284

**Comment by afonsojramos** [comment]
> https://github.com/spicetify/spicetify-cli/blob/80b69628dea963ebff73ba6734967ae024b4efb4/jsHelper/spicetifyWrapper.js#L2370
> 
> 
> https://github.com/spicetify/spicetify-cli/blob/80b69628dea963ebff73ba6734967ae024b4efb4/jsHelper/spicetifyWrapper.js#L2289

As of this PR `upgrade` will continue working, but I suppose it work hurt changing that!

**Comment by rxri** [comment]
i believe he meant these lines:
https://github.com/spicetify/spicetify-cli/blob/80b69628dea963ebff73ba6734967ae024b4efb4/jsHelper/spicetifyWrapper.js#L2372
https://github.com/spicetify/spicetify-cli/blob/80b69628dea963ebff73ba6734967ae024b4efb4/jsHelper/spicetifyWrapper.js#L2373

**Review by rxri — DISMISSED** [review]

**Review by rxri — APPROVED** [review]

**Pull request merged**
