### PR TITLE
feat(lyrics-plus): copy lyrics on right-click & stylings

### LINKED ISSUE #1868: Save Sync/Unsync Lyrics with timestamp
### 📝 Provide a description of the new feature

A save button to download lyrics with time stamp

### ➕ Additional Information

_No response_

### PR DESCRIPTION
**Pull request by kyrie25**
- Resolves #1868 (in a different way than suggested)
Spotify_O8mECE4Xa2
Saves lyrics upon right-click in a `.lrc` text format

- Hover stuff
image

### CODE REVIEW

**Review by ririxichan — APPROVED** [review]

**Review by Tetrax-10 — APPROVED** [review]

**Comment by DragoCubed** [comment]
Think you could go for a different color or opacity so that it looks different?

**Comment by kyrie25** [comment]
> Think you could go for a different color or opacity so that it looks different?

It's best to try to mimic the familiar Spotify experience.
image

**Comment by Tetrax-10** [comment]
Bruh Some one review this with write access.

**Review by afonsojramos — APPROVED** [review]
Awesome!!

**Pull request merged**
