### PR TITLE
feat: toggle in-app update notification

### LINKED ISSUE #2507: Allow hiding `Update Spicetify` button
### 📝 Provide a description of the new feature

I think it would be great if there was an option to hide the `Update Spicetify` button which appears in the top bar. It adds clutter to the top bar and I prefer updating Spicetify when Spotify gets an update so it would be great if that button was optional

### ➕ Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ohitstom**
- removed disable_upgrade_check since it no longer works and is unlikely to be reintroduced
- set check_spicetify_upgrade default value to true
- added check_spicetify_upgrade to Spicetify.Config
- main feat: exit checkForUpdate() function if check_spicetify_upgrade is false (no update topbar button notification)

resolves #2507

### CODE REVIEW

**Review by kyrie25 — APPROVED** [review]

**Review by rxri — APPROVED** [review]

**Comment by rpgdev** [comment]
@ohitstom If the button already appeared, should running `spicetify config check_spicetify_upgrade 0` remove it?

**Comment by ohitstom** [comment]
> @ohitstom If the button already appeared, should running `spicetify config check_spicetify_upgrade 0` remove it?

yep all you need to do is set it to zero and reapply!

**Comment by rpgdev** [comment]
@ohitstom I did that and I'm still seeing the button on spicetify v2.22.2, is that option available on that version? Thought it was.

**Comment by ohitstom** [comment]
> @ohitstom I did that and I'm still seeing the button on spicetify v2.22.2, is that option available on that version? Thought it was.

This was implemented as of 2.23.0, meaning you would have to update to that version before it would take effect, but once you are on that version you will no longer need to update in future 👍🏻

**Comment by rpgdev** [comment]
@ohitstom I just got the update icon on spotify again. Here's my config:
image

check_spicetify_upgrade is 0 but I still got the dialog. What do I need to do so that it doesn't show ever again?

**Comment by ohitstom** [comment]
what version are you on? and what happens if you run spicetify.config in inspect element console

**Comment by rpgdev** [comment]
image

I will need more details about how to "run spicetify.config in inspect element console"

**Comment by ohitstom** [comment]
> image
> 
> I will need more details about how to "run spicetify.config in inspect element console"

run spicetify enable-devtools then inspect element Spotify, go to the console tab and type Spicetify.Config

**Comment by rpgdev** [comment]
image

**Comment by ohitstom** [comment]
expanded?

**Comment by rpgdev** [comment]
image

Btw not sure why it shows a different version than the `version` command...

**Comment by ohitstom** [comment]
try setting check_spicetify_update to 0 and reapplying

**Comment by rpgdev** [comment]
done. So now  I just wait for next time an update arrives?

**Comment by ohitstom** [comment]
> done. So now I just wait for next time an update arrives?

yep if its still an issue open an issue on this repo at that time

**Pull request merged**
