### PR TITLE
changed N to n 😅

### PR DESCRIPTION
**Pull request by LiReNa00**

### CODE REVIEW

**Comment by CharlieS1103** [comment]
Personally I think we should merge this, unless there's a reason we use capital N

**Comment by LiReNa00** [comment]
now dont ask me why I am reopening the request again and gain I messed up real bad 😥

**Comment by ririxidev** [comment]
`N` is capitalized because it's default answer in a code
image
and such I believe it shouldn't be changed

**Comment by theRealPadster** [comment]
The capital indicates a default.

**Comment by CharlieS1103** [comment]
Ah I see, never knew that lol @theRealPadster

**Comment by LiReNa00** [comment]
oh then will Y will be good? I am not sure

**Comment by LiReNa00** [comment]
XD I wonder

**Comment by LiReNa00** [comment]
Oh that is the case .... ok

**Pull request closed without merging**
