### PR TITLE
feat(lyrics-plus): add cutlet japanese transliteration method

### PR DESCRIPTION
**Pull request by faishalirwn**
The current japanese romaji method (kuroshiro) produces a lot of incorrect transliterations. I have compiled some of my findings here: https://www.notion.so/faishalirwn/e9c8db6a52fb43b0acaa6b89e600039a?v=638e78a3c0a540a1ac93bcede6915bad

There is a better library for Japanese transliteration called cutlet: https://github.com/polm/cutlet and it's actively maintained unlike kuroshiro. Unfortunately, it is written in Python, so I have created my own API for it: https://cutlet.1sal.me/docs. The source code for the API is available here: https://github.com/faishalirwn/cutlet-api

This PR adds an alternative romaji method that uses the cutlet API. The API can also correct wrong romaji using the `correction.json` file in the source code repo https://github.com/faishalirwn/cutlet-api/blob/main/corrections.json.

### CODE REVIEW

**Comment by rxri** [comment]
i'm really against this because it's the one who hosts the api and is not used widely and it can go down at any time

**Comment by surfbryce** [comment]
> i'm really against this because you're the one who hosts the api and is not used widely and it can go down at any time. I understand that there are issues with kuroshiro (as seen in your findings) but this one doesn't need self-hosted API to work so atm we will stick with this one

I also want to add that I looked through the source of Cutlet and it would be far better just to convert this to Javascript and have this run locally than through a web-API. There’s no OS level dependencies so if OP really wants it would be better just to start converting it. It would also be contributing to a wider audience more then just Lyrics Plus

**Comment by rxri** [comment]
If they can port it to JavaScript module I will be more than happy to add it

**Comment by afonsojramos** [comment]
Agree to what has been said above!

**Comment by faishalirwn** [comment]
Thank you, I understand the concern, I'll try to learn to the source code and see if I can port it to JavaScript

**Pull request closed without merging**
