### PR TITLE
feat(workflows): use `dry` option for prettier action

### PR DESCRIPTION
**Pull request by SunsetTechuila**
https://github.com/spicetify/spicetify-cli/pull/2719#issuecomment-1851604429

### CODE REVIEW

**Comment by SunsetTechuila** [comment]
tested on my own fork

**Review by rxri — APPROVED** [review]

**Comment by SunsetTechuila** [comment]
no, it still doesn't work https://github.com/SunsetTechuila/spicetify-cli/pull/3/

**Review by afonsojramos — APPROVED** [review]
The issue with this is that you need to ask people to run prettier on their own, which can be annoying in some cases. But at the same time I get the issue

**Comment by SunsetTechuila** [comment]
> The issue with this is that you need to ask people to run prettier on their own

I actually found a way to fix committing, but I think auto-committing would be annoying for contributors (it annoyed me even when I was testing this change lol).
And you don't need to ask contributors for prettifying their code, since they get the notification about the workflow failure.
So I decided to leave this as a check, as it never worked as intended and everything was fine. But if you insist, I'll add auto-commit.

**Comment by afonsojramos** [comment]
I don't insist really! But I remember that in the past people didn't prettify their code. But I think everyone is more aware now, so it should be fine!

**Comment by SunsetTechuila** [comment]
Also, I suggest running the latest prettier with it's defaults on the whole repo again

**Review by rxri — APPROVED** [review]

**Pull request merged**
