### PR TITLE
fix(devtools): use new method to enable devtools

### PR DESCRIPTION
**Pull request by ririxidev**
This method is based on [PhilippIRL](https://gist.github.com/PhilippIRL/97908aba3a78cc0c8d0ab4e9439bf445)'s python script.
It 'patches' offline.bnk that is stored remote configuration, by changing some bytes we can achieve enabled devtools, but it resets every few time so you still need to write `spicetify enable-devtools` many times 😩 

Also changed `spicetify enable-devtool` to `spicetify enable-devtools`

### CODE REVIEW

**Review by CharlieS1103 — APPROVED** [review]
Works on mac!

**Review by ririxidev — COMMENTED** [review]
Works on windows as well

---
Environment: 
```
- Spotify 1.1.84.716.gc5f8b819
- Windows 11 Pro Insider Preview (OS Build 22598.200)
- spicetify v{d63269}
```

**Comment by JulienMaille** [comment]
works fine on 
```
OS: Windows v10.0.22598
Spotify: v1.1.83.956
Spicetify: v2.9.7
```

**Comment by BachoSeven** [comment]
two small comments:

- upon update, the command that I was used to write (`enable-devtool`) didn't work since it was changed to `enable-devtools`, perhaps it couold be mentioned in the release notes;
- `spicetify enable-devtool` fails on my system with: 
```
Can't find the offline.bnk file!
```

Environment:
- spicetify v2.9.7
- Spotify 1.1.84.716.gc5f8b819 (extracted from latest snap)
- Arch Linux

**Comment by ririxidev** [comment]
> two small comments:
> 
> * upon update, the command that I was used to write (`enable-devtool`) didn't work since it was changed to `enable-devtools`, perhaps it couold be mentioned in the release notes;
> * `spicetify enable-devtool` fails on my system with:
> 
> ```
> Can't find the offline.bnk file!
> ```
> 
> Environment:
> 
> * spicetify v2.9.7
> * Spotify 1.1.84.716.gc5f8b819 (extracted from latest snap)
> * Arch Linux

Is `.config/spotify` folder in your home directory then?
also about changing command, I forgot to update help command.

**Comment by ririxidev** [comment]
Can you ping me on spicetify server so we can resolve it there?

**Comment by ririxidev** [comment]
> @BachoSeven It wouldn't be in the users section of it

we already discussed it. Instead of .cache I wrote .config in path.

**Pull request merged**
