### PR TITLE
feat: automated release workflow

### LINKED ISSUE #1502: Create automated release process
## 📝 Provide a description of the new feature

Currently the release process is automated and can be made on windows only. We should move towards an automated release process using GitHub's workflows.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by afonsojramos**
Closes #1502.

This PR is comprised of two main elements.

- [x] Creating an automated release process.
- [x] Adding `upgrade` options for other architectures.
- [x] [create IS_UNIX and IS_WIN variables](https://github.com/spicetify/spicetify-cli/pull/1513/commits/2e246e3082af2b048e64772437a4e5eb375d83ed)
- [x] Trigger AUR/Homebrew release after all releases 

Successful release workflow here: [db852b9](https://github.com/spicetify/spicetify-cli/actions/runs/1912023675)

### CODE REVIEW

**Comment by itsmeow** [comment]
Feature request: remove update.yml and add the following step after release:
```
- name: Request
        uses: https://github.com/fjogeleit/http-request-actionmaster
        with:
          url: https://vps.itsmeow.dev/spicetify-update
          method: GET
```

**Comment by itsmeow** [comment]
Also, I think `on: push` is a bad idea, this should be a manual trigger.

**Comment by afonsojramos** [comment]
> Also, I think on: push is a bad idea, this should be a manual trigger.

@itsmeow What is being used on push is just the normal build job, the release workflow only runs on tags.

```
if: startsWith(github.ref, 'refs/tags/')
```

Regarding the `update.yml` I'll remove it!

**Review by theRealPadster — APPROVED** [review]
I don't really have much experience with github actions etc, but this looks good to me :)

**Pull request merged**
