### PR TITLE
feat(css-map): update classes

### PR DESCRIPTION
**Pull request by SunsetTechuila**

### CODE REVIEW

**Comment by afonsojramos** [comment]
@SunsetTechuila you might have an issue with your local git config for prettier to always fail with you 🤔

**Comment by afonsojramos** [comment]
Are these classes from a new version?

**Comment by SunsetTechuila** [comment]
> you might have an issue with your local git config

haven't changed anything since august

> Are these classes from a new version?

from 1.2.26

**Comment by SunsetTechuila** [comment]
https://github.com/spicetify/spicetify-cli/blob/bc9b20f6727ab12d09a28ef350e4f9f293071866/.github/workflows/prettier.yml#L21

https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#:~:text=With%20the%20exception%20of%20GITHUB_TOKEN%2C%20secrets%20are%20not%20passed%20to%20the%20runner%20when%20a%20workflow%20is%20triggered%20from%20a%20forked%20repository.

**Comment by SunsetTechuila** [comment]
remove this line or add the `dry` option

**Review by rxri — APPROVED** [review]

**Review by afonsojramos — APPROVED** [review]

**Pull request merged**
