### PR TITLE
feat(cmd/update): remove redundant code

### LINKED ISSUE #2655: Spicetify Upgrade Redundant Info Message
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spicetify: 2.27.1
```

### 📝 Description

image

### 📸 Screenshots

_No response_

### PR DESCRIPTION
**Pull request by SunsetTechuila**
it doesn't look like anyone else is going to do this, so yeah
fixes #2655

### CODE REVIEW

**Review by rxri — CHANGES_REQUESTED** [review]
remove the `cmd` variable with the if statement

**Review by rxri — APPROVED** [review]

**Comment by SunsetTechuila** [comment]
Why feat and not fix or chore?

**Comment by rxri** [comment]
`chore` type shouldn't be related to changes that modify the code

**Review by afonsojramos — APPROVED** [review]

**Comment by afonsojramos** [comment]
Thanks @SunsetTechuila!!

**Pull request merged**
