### PR TITLE
fix: compatibility with `1.1.95`

### LINKED ISSUE #1939: Proper installation steps does not work
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
Spotify for macOS (Apple Silicon)
1.1.94.870.gf994cb0b
- Spicetify version: 2.13.1
```

### 📝 Description

I did all the given instructions one by one specified at https://spicetify.app/docs/getting-started. Everything looks good about installation, I didn't get any error but shortcuts do not work at all.

### 📸 Screenshots

`~/.config/spicetify/config-xpui.ini`
```
[Setting]
spotify_path            = /Applications/Spotify.app/Contents/Resources
prefs_path              = /Users/nevzatseferoglu/Library/Application Support/Spotify/prefs
spotify_launch_flags    = 
check_spicetify_upgrade = 0
overwrite_assets        = 0
current_theme           = marketplace
color_scheme            = 
inject_css              = 1
replace_colors          = 1

[Preprocesses]
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1
disable_sentry        = 1
disable_ui_logging    = 1

[AdditionalOptions]
experimental_features = 1
extensions            = 
custom_apps           = marketplace
sidebar_config        = 1
home_config           = 1

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.1.94.870.gf994cb0b
with    = 2.13.1
```

### PR DESCRIPTION
**Pull request by kyrie25**
Resolves #1939 (I hope)
Fix custom apps hook on Spotify version `1.1.95`
image

Backwards compatible & tested.

### CODE REVIEW

**Review by iamririxi — APPROVED** [review]
😄 great job so far. I will try to test backwards compatibility later today

**Comment by iamririxi** [comment]
Doesn't work with `1.1.94.872.g7a9200fe`, `1.1.93.896.g3ae3b4f3`
image

**Comment by kyrie25** [comment]
Had a quick look and I can see why now, will change it up a bit later today.

**Comment by kyrie25** [comment]
Tested and working on Spotify `1.1.94` and `1.1.90`

**Review by CharlieS1103 — APPROVED** [review]

**Comment by CharlieS1103** [comment]
@kyrie25 If you tested backward compatibility all good to me, probably want to wait for ririxi's review though

**Comment by kyrie25** [comment]
React Component hooks are broken again lol, will merge once ready

**Comment by iamririxi** [comment]
> probably want to wait for ririxi's review though

there was no need for that. Kyrie knows how to do stuff right, I just tested backwards compatiblity

**Comment by CharlieS1103** [comment]
@iamririxi Yeah, I just didn't really check in depth and figured better safe than sorry.

**Pull request merged**
