### PR TITLE
ci(github/workflows): add Winget Releaser

### PR DESCRIPTION
**Pull request by sitiom**
- See #708 

[This action](https://github.com/vedantmgoyal2009/winget-releaser) automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

**Before merging this:**
1. Ensure `SPICETIFY_GITHUB_TOKEN` has the `public_repo` scope.

example

2. Fork https://github.com/microsoft/winget-pkgs under @spicetify. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to ensure that it is constantly updated.

You can test out the action inputs in this [playground](https://bittu.eu.org/docs/wr-playground).

If you want to see an example of a PR created using this action, see [microsoft/winget-pkgs/pulls (Pull request has been automatically created using 🛫 WinGet Releaser)](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+Pull+request+has+been+automatically+created+using+%F0%9F%9B%AB+WinGet+Releaser).

### CODE REVIEW

**Review by afonsojramos — APPROVED** [review]

**Comment by afonsojramos** [comment]
Pretty sure that **1** is true, but you can't know until you try it! The rest of them are done as well! So green light from me! 🟢

**Review by rxri — APPROVED** [review]

**Comment by sitiom** [comment]
> > 1. Ensure `SPICETIFY_GITHUB_TOKEN` has the `public_repo` scope.
>
> Pretty sure that **1** is true, but you can't know until you try it! The rest of them are done as well! So green light from me! 🟢

Seems like that's not the case: https://github.com/spicetify/spicetify-cli/actions/runs/4275041072/jobs/7442107876
image

Ping @afonsojramos @rxri

**Comment by rxri** [comment]
PAT tokens have different permissions and such it can't be read-only token
image

**Comment by sitiom** [comment]
> PAT tokens have different permissions and such it can't be read-only token image

Is this a fine-grained token? This is not supported by Winget Releaser yet. From the readme:
> You will need to create a classic Personal Access Token (PAT) with `public_repo` scope. New fine-grained PATs can't access GitHub's GraphQL API, so they aren't supported by this action. Refer to https://github.com/cli/cli/issues/6680 for more information.

**Comment by rxri** [comment]
I mean I think it is PAT from looking on error message, but I may be wrong

**Comment by rxri** [comment]
Well, not sure if it's PATv2 token, but I guess it is if `public_repo` scope is added and it still fails

**Comment by sitiom** [comment]
> PAT tokens have different permissions and such it can't be read-only token image

You were showing this screenshot, which is from the fine-grained token page. Am I not right? Anyways, I have manually created a PR for the update for now: https://github.com/microsoft/winget-pkgs/pull/97838

> Well, not sure if it's PATv2 token, but I guess it is if `public_repo` scope is added and it still fails

Please do check 😅

**Comment by rxri** [comment]
I'm aware, but it's @afonsojramos token so we need to wait for him. Handling it in private right now

**Pull request merged**
